// angular-views/src/app/components/register/register.component.ts
import { Component, OnInit } from '@angular/core';
import { FlashMessagesService } from 'angular2-flash-messages';
import { MyAuthService } from '../../services/auth/myauth.service';
import { ValidateService } from 'src/app/services/validate/validate.service';

@Component({
  selector: 'app-register',
  templateUrl: './register.component.html',
  styleUrls: ['./register.component.css']
})
export class RegisterComponent implements OnInit {

  constructor(
    private validateService: ValidateService,
    private _flashMessagesService: FlashMessagesService,
    private myAuthService: MyAuthService,
  ) { }

  email: String
  username: String
  firstname: String
  lastname: String
  fullname: String
  password: String
  cpassword: String
  provider: String
  email_already: Boolean
  username_already: Boolean
  require: Boolean
  pe: Boolean
  success: Boolean
  errors: Boolean

  ngOnInit() {
  }

  checkEmail() {
    const email = {
      email: this.email
    }
    this.validateService.checkEmail(email).subscribe(data => {
      if(data.result == null || data.result == '' || data.result == 'null') {
        this.email_already = false
      } else {
        this.email_already = true
      }
      // console.log(data)
    })
  }

  checkUsername() {
    const username = {
      username: this.username
    }
    this.validateService.checkUsername(username).subscribe(data => {
      if(data.result == null || data.result == '' || data.result == 'null') {
        this.username_already = false
      } else {
        this.username_already = true
      }
      // console.log(data)
    })
  }

  registerForm() {
    const user = {
      username: this.username,
      email: this.email,
      firstname: this.firstname,
      lastname: this.lastname,
      password: this.password,
      cpassword: this.cpassword,
    }
    var result = this.validateService.validateRegister(user, this.pe, this.email_already, this.username_already )
    if(result == 'required') {
      this.require = true
    } else if(result == 'errors') {
      this.errors = true
    } else {
      this.errors = false
      this.require = false
      this.myAuthService.registerUser(user).subscribe(data => {
        console.log(data)
        if(data.success) {
          this.success = true
          this.username = ''
          this.email = ''
          this.firstname = ''
          this.lastname = ''
          this.password = ''
          this.cpassword = ''
        } else {
          this.success = false
        }
      })
    }
  }

  checkPassword() {
    if(this.password !== this.cpassword) {
      this.pe = true
    } else {
      this.pe = false
    }
  }
}

<div class="container">
    <br><br>
    <div class="row">
        <div class="form col-lg-6">
            <br>
            <h4>Create an account</h4>
            <br>
            <div *ngIf="success" class="alert alert-dismissible alert-success">
                <small>You're successfuly registered, you can log in now</small>
            </div>
            <div *ngIf="errors || email_already || username_already || require || pe || success == false" class="alert alert-dismissible alert-danger">
                <small [style.display]="email_already ? 'block' : 'none'">Email is already exist</small>
                <small [style.display]="username_already ? 'block' : 'none'">Username is already exist</small>
                <small [style.display]="require ? 'block' : 'none'">Please, complete all the fields</small>
                <small [style.display]="pe ? 'block' : 'none'">Password doesn't match with compare password</small>
                <small [style.display]="success == false ? 'block' : 'none'">Somethings went wrong, please try again.</small>
                <small [style.display]="errors ? 'block' : 'none'">Make sure all the field is correct</small>
            </div>
            <br>
            <form>
                <div class="form-group">
                  <label for="exampleInputEmail1">Email address</label>
                  <input type="email" (blur)="checkEmail($event)" [(ngModel)]="email" name="email" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                  <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Username</label>
                    <input type="text" (blur)="checkUsername($event)" [(ngModel)]="username" name="username" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">First name</label>
                    <input type="text" [(ngModel)]="firstname" name="firstname" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">Last name</label>
                    <input type="text" [(ngModel)]="lastname" name="lastname" class="form-control form-control-sm" id="exampleInputEmail1" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                  <label for="exampleInputPassword1">Password</label>
                  <input type="password" (blur)="checkPassword($event)" [(ngModel)]="password" name="password" class="form-control form-control-sm" id="exampleInputPassword1">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">Confirm Password</label>
                    <input type="password" (blur)="checkPassword($event)" [(ngModel)]="cpassword" name="cpassword" class="form-control form-control-sm" id="exampleInputPassword1">
                  </div>
                <button type="button" (click)="registerForm()" class="btn btn-sm btn-primary">Submit</button>
                <span *ngIf="loader" class="loader">
                    <svg-icon src="./assets/svgs/2.svg" [svgStyle]="{ 'width.px':30, 'height.px':30 }"></svg-icon>
                  </span>
            </form>
            <br>
        </div>
    </div>    
</div>

// react-views/src/components/Register.js
import React from 'react';
import './../assets/register.css'
import SimpleReactValidator from 'simple-react-validator';
import axios from 'axios'

class Register extends React.Component {
    constructor() {
        super()
        this.validator = new SimpleReactValidator();
        this.state = {
            email: '',
            username: '',
            password: '',
            confirmPassword: '',
            emailExist: false,
            match: true,
            loading: false,
            success: ''
        };
    }

    inputBlur(event) {
        this.setState({
            ...this.state, [event.target.name]: event.target.value
        })
    }

    checkEmail(event) {
        axios.post('/user/email', {
            email: event.target.value
        }).then(response => {
            this.setState({
                ...this.state, emailExist: (response.data.result == null) ? false : true
            })
        })
    }

    checkPass(event) {
        this.setState({
            match: (this.state.password === this.state.confirmPassword) ? true : false
        })
    }

    submit(event) {
        event.preventDefault()
        if (this.validator.allValid() && this.state.match && !this.state.emailExist) {
            this.setState({
                loading: true
            })
            axios.post(`/user/register`, {
                username: this.state.username,
                email: this.state.email,
                password: this.state.password
            }).then(response => {
                // console.log(response)
                this.setState({
                    loading: false
                })
                this.setState({
                    success: (response.data.success) ? true : false
                })
            })
        } else {
            this.validator.showMessages();
            this.forceUpdate();
        }
    }

    render() {
        return (
            <div className="Register">
            <div className="row">
                <div className="col-lg-4 col-md-6 col-sm-12">
                    <form className="signin">
                        <h4>Create your Account</h4>
                        <br/>
                        <div className="form-group">
                            <label>Email address</label>
                            <input type="email" name="email" className="form-control form-control-sm" placeholder="Enter email" onChange={this.inputBlur.bind(this)} onBlur={this.checkEmail.bind(this)}></input>
                            <small className="error">{this.validator.message('email', this.state.email, 'required|email')}</small>
                            {this.state.emailExist && <small className="error">Email is already exist.</small>}
                        </div>
                        <div className="form-group">
                            <label>Username</label>
                            <input type="text" name="username" className="form-control form-control-sm" placeholder="Username" onChange={this.inputBlur.bind(this)}></input>
                            <small className="error">{this.validator.message('username', this.state.username, 'required')}</small>
                        </div>
                        <div className="form-group">
                            <label>Password</label>
                            <input type="password" name="password" className="form-control form-control-sm" placeholder="Password" onChange={this.inputBlur.bind(this)} onBlur={this.checkPass.bind(this)}></input>
                            <small className="error">{this.validator.message('password', this.state.password, 'required|min:8|max:20')}</small>
                        </div>
                        <div className="form-group">
                            <label>Confirm Password</label>
                            <input type="password" name="confirmPassword" className="form-control form-control-sm" placeholder="Confirm Password" onChange={this.inputBlur.bind(this)} onBlur={this.checkPass.bind(this)}></input>
                            <small className="error">{this.validator.message('confirmPassword', this.state.confirmPassword, 'required|min:8|max:20')}</small>
                            {!this.state.match && <small className="error">Password not match.</small>}
                        </div>
                        <div className="form-group">
                            {this.state.loading && <img className="loader" alt="loader" width="50px" height="50px" src={require('./../assets/loader.svg')} />}
                            {(this.state.success && this.state.success != '') && 
                                <div className="alert alert-dismissible alert-success">
                                    <button type="button" className="close" data-dismiss="alert">&times;</button>
                                    Successfuly registered you can login now.
                                </div>
                            }
                        </div>
                        <button type="submit" onClick={this.submit.bind(this)} className="btn btn-sm btn-primary submit">Submit</button>
                    </form>
                </div>
            </div>
        </div>
        )
    }
}

export default Register;
